////
////  DummyData.swift
////  MovieBookingApp
////
////  Created by Htet Aung Lin on 19/02/2022.
////
//
//import Foundation
//
//let dummyMovieSeats = [
//    MovieSeatVo(title: "A", type: SEAT_TYPE_TEXT),
//    MovieSeatVo(title: "", type: SEAT_TYPE_SPACE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_SPACE),
//    MovieSeatVo(title: "A", type: SEAT_TYPE_TEXT),
//    MovieSeatVo(title: "B", type: SEAT_TYPE_TEXT),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "B", type: SEAT_TYPE_TEXT),
//    MovieSeatVo(title: "C", type: SEAT_TYPE_TEXT),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "C", type: SEAT_TYPE_TEXT),
//    MovieSeatVo(title: "D", type: SEAT_TYPE_TEXT),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "D", type: SEAT_TYPE_TEXT),
//    MovieSeatVo(title: "E", type: SEAT_TYPE_TEXT),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_TAKEN),
//    MovieSeatVo(title: "", type: SEAT_TYPE_TAKEN),
//    MovieSeatVo(title: "", type: SEAT_TYPE_TAKEN),
//    MovieSeatVo(title: "", type: SEAT_TYPE_TAKEN),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "E", type: SEAT_TYPE_TEXT),
//    MovieSeatVo(title: "F", type: SEAT_TYPE_TEXT),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "F", type: SEAT_TYPE_TEXT),
//    MovieSeatVo(title: "G", type: SEAT_TYPE_TEXT),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "", type: SEAT_TYPE_AVAILABLE),
//    MovieSeatVo(title: "G", type: SEAT_TYPE_TEXT),
//]
